Repository thoth-station/ansible-role-postgresql-metrics-exporter, pull requests merged in 2019-11, with the labels that each got.

#1 Created Ansible role for PostgreSQL metrics-exporter
  .github/CODEOWNERS
  README.md
  defaults/main.yml
  meta/main.yml
  tasks/main.yml
  vars/main.yml
Labels: approved, size/L

#2 Add liveness and readiness probes
  tasks/main.yml
Labels: size/S

#4 Correct endpoints for readiness and liveness probes
  tasks/main.yml
Labels: approved, size/XS

#3 Inc initial delay seconds in probes
  tasks/main.yml
Labels: approved, size/XS

#5 Adjust readiness probe to check readiness multiple times
  tasks/main.yml
Labels: approved, size/XS
